// import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ReduxStoreProvider from '@/store/provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'user functions',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReduxStoreProvider>

            {children}
        </ReduxStoreProvider>
      </body>
    </html>
  )
}
